#!/bin/python3

# Import necessary modules
import math
import os
import random
import re
import sys

n = int(input("Please enter the number: "))

# Check if n is even
if n % 2 == 0:
    # If n is even and in the range [6, 20], it's "Weird"
    if 6 <= n <= 20:
        print("Weird")
    # If n is even and greater than 20, it's "Not Weird"
    elif n > 20:
        print("Not Weird")
else:
    # If n is odd and in the range [2, 5], it's "Not Weird"
    if 2 <= n <= 5:
        print("Not Weird")
    else:
        # If n is odd and doesn't meet the above conditions, it's "Weird"
        print("Weird")
